name: Push Prototype to HuggingFace

on:
  push:
    branches: [dev_branch]
  
  # run this workflow manuall from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Deploy Prototype to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://trgardos:$HF_TOKEN@huggingface.co/spaces/dl4ds/tutor_dev main
