name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: DL4DS/dl4ds_tutor
        huggingface_repo_id: dl4ds/dl4ds_tutor
        repo_type: space
        space_sdk: static
        hf_token: ${{ secrets.HF_TOKEN }}

  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Run script
        env:
          LITERAL_AI_API_KEY: ${{ secrets.LITERAL_AI_API_KEY }}
        run: |
          chainlit run code/main.py