name: Create PR for Apps Directory Sync

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout edubotics-core repository
      uses: actions/checkout@v3
      with:
        repository: edubotics-ai/edubotics-core
        ref: main

    - name: Checkout edubotics-app repository
      uses: actions/checkout@v3
      with:
        repository: edubotics-ai/edubotics-app
        ref: main
        path: edubotics-app

    - name: Sync apps directory
      run: |
        rsync -av --delete apps/ edubotics-app/apps/

    - name: Check for changes in apps directory
      run: |
        cd edubotics-app
        git add apps/
        if git diff --quiet; then
          echo "No changes detected in apps directory."
          exit 0
        else
          echo "Changes detected in apps directory."
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Sync Apps Directory"
        branch: "sync-apps-dir"
        title: "Apps Dir Sync"
        body: "This PR syncs the apps/ directory between edubotics-core and edubotics-app repositories."
        labels: "sync"
